AWSTemplateFormatVersion: 2010-09-09
Description: Create a bucket FTF exercise
Parameters:
  BucketName:
    Type: String
    Default: "ftf.vinicius.bucket.exercise"

Resources:
  #Bucket policy to make it public for getting objects
  S3Policy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BucketName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: Allow
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref BucketName
                - /*
            Principal: "*"

  #Bucket allowing public website
  MainBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  WebsiteURL:
    Value: !GetAtt
      - MainBucket
      - WebsiteURL
    Description: URL for website hosted on S3
